### ISSUE TITLE
Add ability to inject custom CSS

### ISSUE THREAD

**Issue by fabis94** [rogden/tailwind-config-viewer#86]
`themeReplacements` are a good start for being able to set CSS variable values, but what if the variables have different values in dark/light theme?

```css
:root {
  --color: #fff;
}

:root.dark {
  --color: #000;
}
```

Thus it would be nice if we could inject custom CSS, even if it has to be CSS-in-JS provided as a string.
